services:
  backend:
    build: .
    ports:
      - "8001:8000"
    networks:
      - music-app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=${BACKEND_DATABASE_URL}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
        db:
          condition: service_healthy
    command: bash -c ""alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: mysql:8.0
    hostname: "db"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - music-app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:

networks:
  music-app:
    driver: bridge